## STAR Fusion
# Fusion gene detection in short-read RNA-seq

import os
import pandas as pd

CTAT_LIB = '/sc/arion/projects/ad-omics/data/references/CTAT/GRCh38_gencode_v37_CTAT_lib_Mar012021/ctat_genome_lib_build_dir'

print(config)
outFolder = config['outFolder']
metadata = config['metadata']

meta = pd.read_csv(metadata, sep = '\t')

print(meta)

samples = meta['sample']

metadata_dict = meta.set_index("sample").T.to_dict()

shell.prefix('ml anaconda3; CONDA_BASE=$(conda info --base); source $CONDA_BASE/etc/profile.d/conda.sh; ml purge; conda deactivate;')

rule all:
    input:
        expand("{outFolder}/{SAMPLE}/star-fusion.fusion_predictions.tsv", outFolder = outFolder, SAMPLE = samples)

rule STAR_fusion:
    output:
        "{outFolder}/{SAMPLE}/star-fusion.fusion_predictions.tsv"
    run:

        r1_file = os.path.join(metadata_dict[wildcards.SAMPLE]["R1"])
        r2_file = os.path.join(metadata_dict[wildcards.SAMPLE]["R2"])
        shell("ml star-fusion;\
             STAR-Fusion --genome_lib_dir {CTAT_LIB} \
             --left_fq {r1_file} \
             --right_fq {r2_file} \
             --output_dir {outFolder}/{wildcards.SAMPLE}")

rule collate:
    input:
        expand("{outFolder}/{SAMPLE}/star-fusion.fusion_predictions.tsv", outFolder = outFolder, SAMPLE = samples)
    output:
        counts = "{outFolder}/{dataCode}.all_fusions_collated.tsv.gz",
        meta = "{outFolder}/{dataCode}.all_fusions_annotation.tsv.gz"
    shell:
        "ml R/4.0.3;"
        "Rscript collate_fusions.R --outFolder {outFolder}"
