# run tiebrush and tiecov on list of samples
# Jack Humphrey 2023
samples = config["samples"]
outFolder = config["outFolder"]

tb_folder = "/sc/arion/projects/ad-omics/data/software/tiebrush"

#shell.prefix('ml anaconda3; CONDA_BASE=$(conda info --base); source $CONDA_BASE/etc/profile.d/conda.sh; ml purge;')


rule all:
    input:
        expand( outFolder + "{sample}.tiebrush.{ext}", sample = samples, ext = ["bam", "bam.bai", "bigwig", "junc.bed"])

rule tiebrush:
    input:
        bam = outFolder + "{sample}.bam",
        bai = outFolder + "{sample}.bam.bai"
    output:
        bam = outFolder + "{sample}.tiebrush.bam",
        bai = outFolder + "{sample}.tiebrush.bam.bai"
    shell:
        "ml samtools/1.9;"
        "{tb_folder}/tiebrush -o {output.bam} {input.bam};"
        "samtools index {output.bam}"

rule tiecov:
    input:
        bam = outFolder + "{sample}.tiebrush.bam",
        bai = outFolder + "{sample}.tiebrush.bam.bai"
    output:
        cov = outFolder + "{sample}.tiebrush.bigwig",
        junc = outFolder + "{sample}.tiebrush.junc.bed"
    shell:
        "ml samtools/1.9;"
        "{tb_folder}/tiecov -W -c {output.cov} -j {output.junc} {input.bam} "
