# run tiebrush and tiecov on list of directories
# merges all BAMs within directory into single BAM
# Jack Humphrey 2023
import glob
import os

inFolder = config["inFolder"]
outFolder = config["outFolder"]

tb_folder = "/sc/arion/projects/ad-omics/data/software/tiebrush"

shell.prefix("ml anaconda3; CONDA_BASE=$(conda info --base); source $CONDA_BASE/etc/profile.d/conda.sh; ml purge;")


rule all:
    input:
        expand( outFolder + "{folder}.tiebrush.{ext}", folder = inFolder, ext = ["bam", "bam.bai", "bigwig", "junc.bed"])

rule tiebrush:
    output:
        bam = outFolder + "{folder}.tiebrush.bam",
        bai = outFolder + "{folder}.tiebrush.bam.bai"
    run:
        print( wildcards.folder )
        BAM_SAMPLES = [ x for x in glob.glob(wildcards.folder + "/*.bam" )]
        print(BAM_SAMPLES)
        shell("ml samtools/1.9; ml gcc; {tb_folder}/tiebrush -o {output.bam} {BAM_SAMPLES}; samtools index {output.bam}")

rule tiecov:
    input:
        bam = outFolder + "{folder}.tiebrush.bam",
        bai = outFolder + "{folder}.tiebrush.bam.bai"
    output:
        cov = outFolder + "{folder}.tiebrush.bigwig",
        junc = outFolder + "{folder}.tiebrush.junc.bed"
    shell:
        "ml samtools/1.9; ml gcc;"
        "{tb_folder}/tiecov -W -c {output.cov} -j {output.junc} {input.bam} "
